// Generated by monorepo-scripts/generate-knip-config.mts
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "../../monorepo-scripts/knip-defaults.js";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
    ignoreBinaries: ["knip", "tsx"],
    ignoreDependencies: ["@eslint/js", "@antfu/eslint-config"],
    // Exports used for rule definitions
    ignoreExportsUsedInFile: true,
    rules: {
        exports: "off",
    },
});
