// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
    ignoreBinaries: ["knip", "tsx"],
    ignoreDependencies: ["@eslint/js", "@antfu/eslint-config"],
    // Exports used for rule definitions
    ignoreExportsUsedInFile: true,
    rules: {
        exports: "off",
    },
});
